'use client';

import { useState } from 'react';
import { ChevronRight, ChevronLeft, CheckCircle, Circle, Upload, CheckCircle2, Mail, Clock, Loader2 } from 'lucide-react';
import Link from 'next/link';
import axios from 'utils/axios.js'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';

const KycRegistration = () => {
  const [step, setStep] = useState(1);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    // Personal Info
    firstName: '',
    lastName: '',
    phone: '',
    email: '',
    gender: '',
    dob: '',
    address: '',
    
    // Nominee Info
    nomineeName: '',
    nomineeRelation: '',
    nomineeDob: '',
    
    // KYC Info
    aadharNo: '',
    pan: '',
    aadharPhoto: null,
    panPhoto: null,
    userPhoto: null,
    passbookPhoto: null,
    
    // Bank Details
    bankName: '',
    accountHolder: '',
    accountNumber: '',
    ifscCode: '',
    
    // Terms
    agreedToTerms: false
  });

  const [errors, setErrors] = useState({});

  const validateStep = (step) => {
    const newErrors = {};
    
    if (step === 1) {
      if (!formData.firstName.trim()) newErrors.firstName = 'First name is required';
      if (!formData.lastName.trim()) newErrors.lastName = 'Last name is required';
      if (!formData.phone.trim()) newErrors.phone = 'Phone is required';
      if (!formData.email.trim()) newErrors.email = 'Email is required';
      else if (!/^\S+@\S+\.\S+$/.test(formData.email)) newErrors.email = 'Email is invalid';
  
      if (!formData.gender) newErrors.gender = 'Gender is required';
      if (!formData.dob) newErrors.dob = 'Date of birth is required';
      if (!formData.address.trim()) newErrors.address = 'Address is required';
    }
    
    if (step === 2) {
      if (!formData.aadharNo.trim()) newErrors.aadharNo = 'Aadhar number is required';
      if (!formData.pan.trim()) newErrors.pan = 'PAN number is required';
      if (!formData.aadharPhoto) newErrors.aadharPhoto = 'Aadhar photo is required';
      if (!formData.panPhoto) newErrors.panPhoto = 'PAN photo is required';
      if (!formData.userPhoto) newErrors.userPhoto = 'User photo is required';
      if (!formData.passbookPhoto) newErrors.passbookPhoto = 'Passbook photo is required';
      if (!formData.nomineeName.trim()) newErrors.nomineeName = 'Nominee name is required';
      if (!formData.nomineeRelation.trim()) newErrors.nomineeRelation = 'Nominee relation is required';
      if (!formData.nomineeDob) newErrors.nomineeDob = 'Nominee date of birth is required';
    }
    
    if (step === 3) {
      if (!formData.bankName.trim()) newErrors.bankName = 'Bank name is required';
      if (!formData.accountHolder.trim()) newErrors.accountHolder = 'Account holder name is required';
      if (!formData.accountNumber.trim()) newErrors.accountNumber = 'Account number is required';
      if (!formData.ifscCode.trim()) newErrors.ifscCode = 'IFSC code is required';
      if (!formData.agreedToTerms) newErrors.agreedToTerms = 'You must agree to terms';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e) => {
    const { name, value, type, files } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'file' ? files[0] : value
    }));
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => {
        const newErrors = {...prev};
        delete newErrors[name];
        return newErrors;
      });
    }
  };

  const nextStep = () => {
    if (validateStep(step)) {
      setStep(prev => prev + 1);
    }
  };

  const prevStep = () => setStep(prev => prev - 1);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (validateStep(3)) {
      setIsSubmitting(true);
      try {
        // Create FormData for multipart/form-data submission
        const submitData = new FormData();
        
        // Append all text fields (password removed - will be generated by admin)
        submitData.append('firstName', formData.firstName);
        submitData.append('lastName', formData.lastName);
        submitData.append('email', formData.email);
        // Password is no longer sent - admin will generate and send it after approval
        submitData.append('phone', formData.phone);
        submitData.append('gender', formData.gender);
        submitData.append('dob', formData.dob);
        submitData.append('address', formData.address);
        submitData.append('aadharNo', formData.aadharNo);
        submitData.append('pan', formData.pan);
        submitData.append('nomineeName', formData.nomineeName);
        submitData.append('nomineeRelation', formData.nomineeRelation);
        submitData.append('nomineeDob', formData.nomineeDob);
        submitData.append('bankName', formData.bankName);
        submitData.append('accountHolder', formData.accountHolder);
        submitData.append('accountNumber', formData.accountNumber);
        submitData.append('ifscCode', formData.ifscCode);
        
        // Append file fields
        if (formData.aadharPhoto) submitData.append('aadharPhoto', formData.aadharPhoto);
        if (formData.panPhoto) submitData.append('panPhoto', formData.panPhoto);
        if (formData.userPhoto) submitData.append('userPhoto', formData.userPhoto);
        if (formData.passbookPhoto) submitData.append('passbookPhoto', formData.passbookPhoto);
        
        console.log("Submitting registration data...");
        
        const response = await axios.post('/user/register', submitData, {
          headers: {
            'Content-Type': 'multipart/form-data'
          },
          timeout: 30000 // 30 seconds timeout for file uploads
        });
        
        console.log("Registration Response:", response.data);
        
        if (response.data && response.data.status === 'success') {
          // Show success modal instead of alert
          setShowSuccessModal(true);
        } else {
          alert('Registration completed but received unexpected response. Please check your email for updates.');
          setIsSubmitting(false);
        }
      } catch (error) {
        console.error("Registration Error:", error);
        
        // Handle timeout errors specifically
        if (error.code === 'ECONNABORTED' || error.message?.includes('timeout')) {
          alert('Request timed out. This might be due to slow network or large file uploads. Please check your internet connection and try again with smaller images if possible.');
          return;
        }
        
        // Handle network errors
        if (error.code === 'ERR_NETWORK' || !error.response) {
          alert('Network error. Please check your internet connection and try again.');
          return;
        }
        
        const errorMessage = error.response?.data?.message || 
                            error.response?.data?.error ||
                            error.message || 
                            'Registration failed. Please try again.';
        
        // Show specific error messages
        if (error.response?.data?.errors) {
          alert(`Registration failed:\n${error.response.data.errors.join('\n')}`);
        } else {
          alert(errorMessage);
        }
      } finally {
        setIsSubmitting(false);
      }
    }
  };

  const handleCloseModal = () => {
    setShowSuccessModal(false);
    window.location.href = '/login';
  };

  return (
    <div className="min-h-[calc(100vh-64px)] w-full bg-[#D0E2D2] flex items-center justify-center relative overflow-hidden pt-20 pb-8">
      {/* Background elements */}
      <div className="absolute inset-0 overflow-hidden opacity-20">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 md:w-96 md:h-96 bg-[#43B852] rounded-full blur-3xl"></div>
        <div className="absolute top-1/2 right-1/4 w-56 h-56 md:w-80 md:h-80 bg-[#0E1F1B] rounded-full blur-3xl"></div>
        <div className="absolute bottom-1/4 left-1/3 w-48 h-48 md:w-72 md:h-72 bg-[#43B852] rounded-full blur-3xl opacity-70"></div>
      </div>

      {/* Main container */}
      <div className="relative z-10 w-full max-w-4xl mx-4 my-4 bg-white bg-opacity-90 backdrop-blur-sm rounded-3xl shadow-2xl overflow-hidden">
        {/* Progress Steps */}
        <div className="bg-[#0E1F1B] p-4">
          <div className="flex justify-between items-center text-white relative">
            {/* Progress line */}
            <div className="absolute top-4 left-16 right-16 h-1 bg-[#D0E2D2]">
              <div 
                className="h-full bg-[#43B852] transition-all duration-300 ease-in-out" 
                style={{ 
                  width: step === 1 ? '0%' : step === 2 ? '50%' : '100%' 
                }}
              ></div>
            </div>
            
            {[1, 2, 3].map((stepNumber) => (
              <div key={stepNumber} className="flex flex-col items-center z-10">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step >= stepNumber ? 'bg-[#43B852]' : 'bg-[#D0E2D2]'}`}>
                  {step > stepNumber ? (
                    <CheckCircle className="h-5 w-5 text-white" />
                  ) : (
                    <Circle className={`h-5 w-5 ${step === stepNumber ? 'text-white' : 'text-[#0E1F1B]'}`} />
                  )}
                </div>
                <span className="text-xs mt-1">
                  {stepNumber === 1 && 'Personal'}
                  {stepNumber === 2 && 'KYC'}
                  {stepNumber === 3 && 'Bank'}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Form Content */}
        <div className="p-6 md:p-8 relative">
          {isSubmitting && (
            <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-10 rounded-3xl flex items-center justify-center">
              <div className="flex flex-col items-center gap-3">
                <Loader2 className="h-8 w-8 animate-spin text-[#43B852]" />
                <p className="text-[#0E1F1B] font-semibold">Creating your account...</p>
                <p className="text-sm text-gray-600">Please wait while we process your registration</p>
              </div>
            </div>
          )}
          <h2 className="text-2xl md:text-3xl font-bold text-[#0E1F1B] mb-6 text-center">
            Create Your Account
          </h2>

          <form onSubmit={handleSubmit} className={isSubmitting ? 'pointer-events-none opacity-60' : ''}>
            {/* Step 1: Personal Information */}
            {step === 1 && (
              <div className="space-y-4">
                <h3 className="text-xl font-semibold text-[#43B852] mb-4">Personal Information</h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">First Name</label>
                    <input
                      type="text"
                      name="firstName"
                      value={formData.firstName}
                      onChange={handleChange}
                      placeholder="Enter your first name"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.firstName && <p className="text-red-500 text-xs mt-1">{errors.firstName}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Last Name</label>
                    <input
                      type="text"
                      name="lastName"
                      value={formData.lastName}
                      onChange={handleChange}
                      placeholder="Enter your last name"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.lastName && <p className="text-red-500 text-xs mt-1">{errors.lastName}</p>}
                  </div>
                </div>

                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Email Address</label>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    placeholder="Enter your email address"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.email && <p className="text-red-500 text-xs mt-1">{errors.email}</p>}
                </div>

                <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
                  <p className="text-sm text-blue-800">
                    <strong>Note:</strong> Your login password will be generated by the admin and sent to your email once your profile is approved.
                  </p>
                </div>

                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Phone Number</label>
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    placeholder="Enter your phone number"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.phone && <p className="text-red-500 text-xs mt-1">{errors.phone}</p>}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Gender</label>
                    <select
                      name="gender"
                      value={formData.gender}
                      onChange={handleChange}
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    >
                      <option value="">Select Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                      <option value="Other">Other</option>
                    </select>
                    {errors.gender && <p className="text-red-500 text-xs mt-1">{errors.gender}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Date of Birth</label>
                    <input
                      type="date"
                      name="dob"
                      value={formData.dob}
                      onChange={handleChange}
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.dob && <p className="text-red-500 text-xs mt-1">{errors.dob}</p>}
                  </div>
                </div>

                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Address</label>
                  <textarea
                    name="address"
                    value={formData.address}
                    onChange={handleChange}
                    placeholder="Enter your full address"
                    rows="3"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.address && <p className="text-red-500 text-xs mt-1">{errors.address}</p>}
                </div>

                <div className="flex justify-end mt-6">
                  <button
                    type="button"
                    onClick={nextStep}
                    className="bg-[#43B852] hover:bg-[#0E1F1B] text-white py-2 px-6 rounded-xl flex items-center disabled:opacity-50"
                    disabled={!formData.firstName || !formData.lastName || !formData.email || !formData.phone || !formData.gender || !formData.dob || !formData.address}
                  >
                    Next <ChevronRight className="ml-1 h-5 w-5" />
                  </button>
                </div>
              </div>
            )}

            {/* Step 2: KYC Information */}
            {step === 2 && (
              <div className="space-y-4">
                <h3 className="text-xl font-semibold text-[#43B852] mb-4">KYC Information</h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Aadhar Number</label>
                    <input
                      type="text"
                      name="aadharNo"
                      value={formData.aadharNo}
                      onChange={handleChange}
                      placeholder="Enter your Aadhar number"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.aadharNo && <p className="text-red-500 text-xs mt-1">{errors.aadharNo}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">PAN Number</label>
                    <input
                      type="text"
                      name="pan"
                      value={formData.pan}
                      onChange={handleChange}
                      placeholder="Enter your PAN number"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.pan && <p className="text-red-500 text-xs mt-1">{errors.pan}</p>}
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Aadhar Card Photo</label>
                    <label className="flex flex-col items-center justify-center h-28 border-2 border-dashed border-[#D0E2D2] rounded-xl cursor-pointer hover:bg-[#D0E2D2]/10">
                      <Upload className="h-5 w-5 text-[#43B852] mb-1" />
                      <span className="text-xs text-center text-[#0E1F1B]">
                        {formData.aadharPhoto ? formData.aadharPhoto.name : 'Upload Aadhar'}
                      </span>
                      <input
                        type="file"
                        name="aadharPhoto"
                        onChange={handleChange}
                        className="hidden"
                        accept="image/*"
                        required
                      />
                    </label>
                    {errors.aadharPhoto && <p className="text-red-500 text-xs mt-1">{errors.aadharPhoto}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">PAN Card Photo</label>
                    <label className="flex flex-col items-center justify-center h-28 border-2 border-dashed border-[#D0E2D2] rounded-xl cursor-pointer hover:bg-[#D0E2D2]/10">
                      <Upload className="h-5 w-5 text-[#43B852] mb-1" />
                      <span className="text-xs text-center text-[#0E1F1B]">
                        {formData.panPhoto ? formData.panPhoto.name : 'Upload PAN'}
                      </span>
                      <input
                        type="file"
                        name="panPhoto"
                        onChange={handleChange}
                        className="hidden"
                        accept="image/*"
                        required
                      />
                    </label>
                    {errors.panPhoto && <p className="text-red-500 text-xs mt-1">{errors.panPhoto}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Passport Size Photo</label>
                    <label className="flex flex-col items-center justify-center h-28 border-2 border-dashed border-[#D0E2D2] rounded-xl cursor-pointer hover:bg-[#D0E2D2]/10">
                      <Upload className="h-5 w-5 text-[#43B852] mb-1" />
                      <span className="text-xs text-center text-[#0E1F1B]">
                        {formData.userPhoto ? formData.userPhoto.name : 'Upload Photo'}
                      </span>
                      <input
                        type="file"
                        name="userPhoto"
                        onChange={handleChange}
                        className="hidden"
                        accept="image/*"
                        required
                      />
                    </label>
                    {errors.userPhoto && <p className="text-red-500 text-xs mt-1">{errors.userPhoto}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Passbook Photo</label>
                    <label className="flex flex-col items-center justify-center h-28 border-2 border-dashed border-[#D0E2D2] rounded-xl cursor-pointer hover:bg-[#D0E2D2]/10">
                      <Upload className="h-5 w-5 text-[#43B852] mb-1" />
                      <span className="text-xs text-center text-[#0E1F1B]">
                        {formData.passbookPhoto ? formData.passbookPhoto.name : 'Upload Passbook'}
                      </span>
                      <input
                        type="file"
                        name="passbookPhoto"
                        onChange={handleChange}
                        className="hidden"
                        accept="image/*"
                        required
                      />
                    </label>
                    {errors.passbookPhoto && <p className="text-red-500 text-xs mt-1">{errors.passbookPhoto}</p>}
                  </div>
                </div>

                <h3 className="text-xl font-semibold text-[#43B852] mb-4 mt-6">Nominee Information</h3>
                
                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Nominee Name</label>
                  <input
                    type="text"
                    name="nomineeName"
                    value={formData.nomineeName}
                    onChange={handleChange}
                    placeholder="Enter nominee's full name"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.nomineeName && <p className="text-red-500 text-xs mt-1">{errors.nomineeName}</p>}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Nominee Relation</label>
                    <input
                      type="text"
                      name="nomineeRelation"
                      value={formData.nomineeRelation}
                      onChange={handleChange}
                      placeholder="e.g., Spouse, Parent, Sibling"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.nomineeRelation && <p className="text-red-500 text-xs mt-1">{errors.nomineeRelation}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Nominee Date of Birth</label>
                    <input
                      type="date"
                      name="nomineeDob"
                      value={formData.nomineeDob}
                      onChange={handleChange}
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.nomineeDob && <p className="text-red-500 text-xs mt-1">{errors.nomineeDob}</p>}
                  </div>
                </div>

                <div className="flex justify-between mt-6">
                  <button
                    type="button"
                    onClick={prevStep}
                    className="bg-[#D0E2D2] hover:bg-[#0E1F1B] text-[#0E1F1B] hover:text-white py-2 px-6 rounded-xl flex items-center"
                  >
                    <ChevronLeft className="mr-1 h-5 w-5" /> Back
                  </button>
                  <button
                    type="button"
                    onClick={nextStep}
                    className="bg-[#43B852] hover:bg-[#0E1F1B] text-white py-2 px-6 rounded-xl flex items-center disabled:opacity-50"
                    disabled={!formData.aadharNo || !formData.pan || !formData.aadharPhoto || !formData.panPhoto || !formData.userPhoto || !formData.passbookPhoto || !formData.nomineeName || !formData.nomineeRelation || !formData.nomineeDob}
                  >
                    Next <ChevronRight className="ml-1 h-5 w-5" />
                  </button>
                </div>
              </div>
            )}

            {/* Step 3: Bank Details */}
            {step === 3 && (
              <div className="space-y-4">
                <h3 className="text-xl font-semibold text-[#43B852] mb-4">Bank Details</h3>
                
                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Bank Name</label>
                  <input
                    type="text"
                    name="bankName"
                    value={formData.bankName}
                    onChange={handleChange}
                    placeholder="Enter your bank name"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.bankName && <p className="text-red-500 text-xs mt-1">{errors.bankName}</p>}
                </div>

                <div>
                  <label className="block text-[#0E1F1B] text-sm mb-1">Account Holder Name</label>
                  <input
                    type="text"
                    name="accountHolder"
                    value={formData.accountHolder}
                    onChange={handleChange}
                    placeholder="Enter account holder name"
                    className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                    required
                  />
                  {errors.accountHolder && <p className="text-red-500 text-xs mt-1">{errors.accountHolder}</p>}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">Account Number</label>
                    <input
                      type="text"
                      name="accountNumber"
                      value={formData.accountNumber}
                      onChange={handleChange}
                      placeholder="Enter your account number"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.accountNumber && <p className="text-red-500 text-xs mt-1">{errors.accountNumber}</p>}
                  </div>

                  <div>
                    <label className="block text-[#0E1F1B] text-sm mb-1">IFSC Code</label>
                    <input
                      type="text"
                      name="ifscCode"
                      value={formData.ifscCode}
                      onChange={handleChange}
                      placeholder="Enter bank IFSC code"
                      className="w-full bg-[#D0E2D2]/20 text-[#0E1F1B] px-4 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#43B852] border border-[#D0E2D2]"
                      required
                    />
                    {errors.ifscCode && <p className="text-red-500 text-xs mt-1">{errors.ifscCode}</p>}
                  </div>
                </div>

                <div className="flex items-center mt-4">
                  <div className="flex items-center">
                    <input
                      type="checkbox"
                      id="terms"
                      name="agreedToTerms"
                      checked={formData.agreedToTerms}
                      onChange={(e) => setFormData(prev => ({ ...prev, agreedToTerms: e.target.checked }))}
                      className="h-5 w-5 rounded border-[#D0E2D2] text-[#43B852] focus:ring-[#43B852] cursor-pointer"
                      required
                    />
                    <label htmlFor="terms" className="ml-2 text-sm text-[#0E1F1B]">
                      I agree to the <Link href="/terms" className="text-[#43B852] hover:underline">Terms & Conditions</Link>
                    </label>
                  </div>
                  {errors.agreedToTerms && <p className="text-red-500 text-xs ml-2">{errors.agreedToTerms}</p>}
                </div>

                <div className="flex justify-between mt-6">
                  <button
                    type="button"
                    onClick={prevStep}
                    className="bg-[#D0E2D2] hover:bg-[#0E1F1B] text-[#0E1F1B] hover:text-white py-2 px-6 rounded-xl flex items-center"
                  >
                    <ChevronLeft className="mr-1 h-5 w-5" /> Back
                  </button>
                  <button
                    type="submit"
                    disabled={isSubmitting || !formData.bankName || !formData.accountHolder || !formData.accountNumber || !formData.ifscCode || !formData.agreedToTerms}
                    className="bg-[#43B852] hover:bg-[#0E1F1B] text-white py-2 px-6 rounded-xl flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                  >
                    {isSubmitting ? (
                      <>
                        <Loader2 className="h-5 w-5 animate-spin" />
                        Creating Account...
                      </>
                    ) : (
                      'Register Now'
                    )}
                  </button>
                </div>
              </div>
            )}
          </form>

          <div className="mt-6 text-center text-sm text-[#0E1F1B]">
            Already have an account? <Link href="/login" className="text-[#43B852] hover:underline">Login here</Link>
          </div>
        </div>
      </div>

      {/* Success Modal */}
      <Dialog open={showSuccessModal} onOpenChange={setShowSuccessModal}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <div className="flex items-center justify-center mb-4">
              <div className="rounded-full bg-green-100 p-3">
                <CheckCircle2 className="h-12 w-12 text-[#43B852]" />
              </div>
            </div>
            <DialogTitle className="text-2xl text-center text-[#0E1F1B]">
              Profile Registered Successfully!
            </DialogTitle>
            <DialogDescription className="text-center pt-4">
              <div className="space-y-4">
                <p className="text-[#0E1F1B] text-base">
                  Your registration has been submitted successfully. Our admin team will review your profile shortly.
                </p>
                
                <div className="bg-[#e7f3ff] border-l-4 border-[#2196F3] p-4 rounded-lg space-y-3">
                  <div className="flex items-start gap-3">
                    <Clock className="h-5 w-5 text-[#2196F3] mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="font-semibold text-[#0E1F1B]">Please Wait for Approval</p>
                      <p className="text-sm text-gray-600 mt-1">
                        Your profile is currently under review. You'll receive an email notification once it's processed.
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex items-start gap-3">
                    <Mail className="h-5 w-5 text-[#2196F3] mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="font-semibold text-[#0E1F1B]">Login Password</p>
                      <p className="text-sm text-gray-600 mt-1">
                        After verification, you will receive your login password via email to access your account.
                      </p>
                    </div>
                  </div>
                </div>

                <p className="text-sm text-gray-500 pt-2">
                  Check your email inbox (and spam folder) for updates on your profile status.
                </p>
              </div>
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="sm:justify-center pt-4">
            <Button
              onClick={handleCloseModal}
              className="bg-[#43B852] hover:bg-[#0E1F1B] text-white px-8 py-2"
            >
              Go to Login
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default KycRegistration;